#!/bin/bash

while getopts abc:D: opt 2>/dev/null
do
	case $opt in
		a) echo "Option -a" ;;
		b) echo "Option -b" ;;
		c) echo "option -c : ($OPTARG)" ;;
		D) echo "opton -D : ($OPTARG)" ;;
		?) echo "unbekante option"
		break; 
	esac 
done
