#!/bin/bash

[ -z "$0" ] && echo $0
[ -z "$1" ] && echo $1
[ -z "$2" ] && echo $2
[ -z "$3" ] && echo $3
[ -z "$4" ] && echo $4
[ -z "$5" ] && echo $5
[ -z "$6" ] && echo $6
[ -z "$7" ] && echo $7
[ -z "$8" ] && echo $8
[ -z "$9" ] && echo $9
