#!/bin/bash

PS3='Bitte geben Sie eine Zahl ein: '

select opt in "Brot" "Käse" "Schinken" "Beenden"
do
	case $opt in 
		"Brot")		echo "Sie haben Nr 1, $opt gewählt" ;;
		"Käse") 	echo "Sie haben Nr 2, $opt gewählt" ;;
		"Schinken")	echo "Sie haben Nr 3, $opt gewählt" ;;
		"Beenden" 	break;
	esac
done
